### ISSUE TITLE
Unable to generate step definition file from feature in cypress-cucumber-preprocessor

### ISSUE THREAD

**Issue by avaiyarasi** [dmoerland95/step-definition-generator#1]
Hi,
In the Readme.md file the installation command is mentioned as 'apm install step-definition-generator'. I think it is 'npm install step-definition-generator'? However, when I tried this I get E404- Not found,  'step-definition-generator@latest' is not in the npm registry. Can you let me know if this is still available to be used? 

When I installed the VS code plugin 'cypress-cucumber-steps', I don't really get the command 'Generate steps from feature file' on my feature file. 

Can you take a look at this? Thank you in advance.

**Comment by dylanmoerland** [comment]
hi @avaiyarasi this repository is a plugin for Atom not for VScode

apm install step-definition-generator is the correct command, apm is the command line interface for the Atom ide (https://atom.io/)

I recreated this plugin for VSCode now as well, you can find it on this link
https://github.com/dylanmoerland/cypress-cucumbur-steps

Here's an example of it working

![example](https://user-images.githubusercontent.com/4416236/82141086-d014ce80-9833-11ea-9661-d7ec0c8bb081.gif)

If you have any issues regarding the VSCode plugin could you post them in Issues on the repository I just shared?
